### PR TITLE
layout changes and general fixes

### PR DESCRIPTION
**Pull request by sharunkumar**

### CODE REVIEW

**Review by arunsathiya — COMMENTED** [review]
I like the direction this is going but spacing is a bit off. 

Before:

image


After:

image

No strong preference for the "before" version, but is your proposed version intentionally tight?

**Comment by arunsathiya** [comment]
@sharunkumar if you want to propose this new component upstream, here you go:

- https://github.com/MaeWolff/astro-portfolio-template/

**Comment by sharunkumar** [comment]
> No strong preference for the "before" version, but is your proposed version intentionally tight?

idk, I thought it was a bit too wide for this type of content

**Comment by arunsathiya** [comment]
I like https://github.com/arunsathiya/portfolio/pull/5/commits/bfc36f9030b31aaa1dde5dde65dc0eba595fd9a1. 👍🏼

**Comment by sharunkumar** [comment]
@arunsathiya these changes should be fine for now

**Comment by arunsathiya** [comment]
Merged using the [gh CLI](https://github.com/cli/cli/). ❤️

**Pull request merged**
